import React from 'react';

const Contact = () => {
    return (
        <div className='px-8'>
        <h2 className='font-bold text-2xl text-center mt-4 mb-8'>Contact us</h2>
        <p className='font-semibold text-md text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates earum quidem aut explicabo magni tempora molestiae enim, perspiciatis dolor dolorem voluptatem voluptatum nobis culpa. Iusto perferendis sit quia similique quisquam. Dolorem minima impedit esse vel rem! Exercitationem, perferendis quis magni quo praesentium doloremque nostrum unde ad? Autem recusandae magnam dolorem laudantium ipsum ipsam officia ab, dignissimos in blanditiis, culpa optio neque consequatur tempora officiis sunt eius laborum reiciendis id, impedit dolore quo! Nisi soluta eum placeat sit aperiam consequuntur rerum earum. <br /> <br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae error doloremque sunt placeat, reiciendis impedit, sint asperiores minus ut id iste voluptate non qui ipsa consequatur, architecto aperiam harum. Itaque voluptatum pariatur temporibus eligendi. Adipisci provident voluptas nisi at corrupti nam porro accusamus repellat alias. Sit quo, earum tenetur dicta enim suscipit! Architecto maxime, ad, ratione odio ut placeat alias, labore dolores nostrum commodi minima esse deleniti reprehenderit id sapiente repudiandae mollitia fugit dolorum maiores culpa nam quaerat! Distinctio mollitia, obcaecati beatae corporis ratione possimus eius laboriosam incidunt ullam nostrum nesciunt amet maiores cum veniam. A, corrupti tempora? Quis quas adipisci autem veritatis at ea? Rerum maiores, amet quae illo cupiditate fuga nesciunt? Iste delectus qui non obcaecati vero nihil ipsum laborum aut facere sit dolor assumenda cum similique libero, nisi inventore deserunt ducimus veniam repellat omnis illum rerum explicabo quo? Illo, ullam. Aliquam corporis laborum cupiditate eum, quia voluptatum? <br /> <br />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab facilis eligendi ullam, neque vel aliquid ex odit? Iure tempora rem velit repudiandae cum asperiores voluptas exercitationem, dolore repellendus odio, veritatis temporibus rerum facere laborum optio id adipisci sit minus quibusdam deserunt laudantium iusto aut. Saepe unde magnam totam ipsam facilis, facere nihil, sunt nam illo similique qui excepturi, enim maxime esse. Odio eum nesciunt animi soluta atque reprehenderit maiores minima excepturi, molestiae natus, adipisci iure sunt, quasi quidem aliquam ipsum deleniti ut at. Ea cupiditate omnis quidem itaque hic, perferendis explicabo nesciunt illum tenetur repudiandae sed odit, reprehenderit harum illo, qui repellendus quisquam ab id atque quas delectus odio veniam consequuntur. Dolore mollitia magni error eum pariatur deleniti totam, illum alias accusantium at debitis ratione amet, nihil sint dolorem laborum explicabo exercitationem tenetur ea excepturi iusto autem asperiores enim. Reprehenderit dolorum odit natus fuga tempora!</p>
    </div>
    );
};

export default Contact;